@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMDAyIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImp0aSI6IjE3MTllODZlLTQzYTUtNDg1NS04Y2U1LTA5MmQzNDg0ZDYzMiIsImV4cCI6MTc4NzY3NzkzNywiaXNzIjoiVGFza0FwaSIsImF1ZCI6IlRhc2tBcGlDbGllbnQifQ.gCKHesBC1kRUq1NqS7F_m75d7g4CWaADQDclY_XcnM4
@admintoken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMDA0IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJqdGkiOiJhZjY3OWMyYS1jMjc1LTQ0MGUtODJlOS1jNTZiNzM5ZmI4NWQiLCJleHAiOjE3ODk3NDM0ODksImlzcyI6IlRhc2tBcGkiLCJhdWQiOiJUYXNrQXBpQ2xpZW50In0._ym50QjJXA8ScdGw5qEKOKOnxkUOoUMDWQg6t7JxFW4

GET http://localhost:5282/api/users
Authorization: Bearer {{admintoken}}


###
GET http://localhost:5282/api/users/1002
Authorization: Bearer {{token}}


###
POST http://localhost:5282/api/users
Content-Type: application/json
Authorization: Bearer {{admintoken}}


{
  "username": "adalia",
  "email": "adalia@example.com",
  "password": "<74677422Ka>"
}

###
PUT http://localhost:5282/api/users/1002
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "username": "Daniel_Porras",
  "email": "daniel@example.com",
  "role" : "Admin"
}


###
DELETE http://localhost:5282/api/users/1004
Authorization: Bearer {{admintoken}}


###
POST http://localhost:5282/api/Users/1002/promote
Content-Type: application/json
Authorization: Bearer {{admintoken}}

###
POST http://localhost:5282/api/Users/1004/demote
Content-Type: application/json
Authorization: Bearer {{admintoken}}

###
POST http://localhost:5282/api/Users/2/toggle-active
Content-Type: application/json
Authorization: Bearer {{admintoken}}
